const vocabulary = [
    {
        word: "逐渐",
        pinyin: "zhújiàn",
        meaning: "ค่อยๆ, ทีละน้อย",
        example: "天气逐渐变冷了。",
        examplePinyin: "Tiānqì zhújiàn biàn lěng le.",
        translation: "อากาศค่อยๆ หนาวขึ้นแล้ว",
    },

    {
        word: "承担",
        pinyin: "chéngdān",
        meaning: "รับผิดชอบ, แบกรับ",
        example: "我们应该承担自己的责任。",
        examplePinyin: "Wǒmen yīnggāi chéngdān zìjǐ de zérèn.",
        translation: "พวกเราควรรับผิดชอบต่อหน้าที่ของตัวเอง",
    },

    {
        word: "爱护",
        pinyin: "ài hù",
        meaning: "รักษา, ดูแล",
        example: "我们应该爱护环境。",
        examplePinyin: "Wǒmen yīnggāi àihù huánjìng.",
        translation: "พวกเราควรรักษาสิ่งแวดล้อม",
    },

    {
        word: "爱惜",
        pinyin: "ài xī",
        meaning: "รัก, หวงแหน",
        example: "我们要爱惜自己的身体。",
        examplePinyin: "Wǒmen yào àixī zìjǐ de shēntǐ.",
        translation: "เราต้องดูแลและทะนุถนอมร่างกายของตัวเอง",
    },

    {
        word: "财产",
        pinyin: "cáichǎn",
        meaning: "ทรัพย์สิน, ทรัพย์สมบัติ",
        example: "请保护好自己的财产。",
        examplePinyin: "Qǐng bǎohù hǎo zìjǐ de cáichǎn.",
        translation: "กรุณาดูแลทรัพย์สินของตัวเองให้ดี",
    },

    {
        word: "输",
        pinyin: "shū",
        meaning: "แพ้, ขาดทุน, สูญเสีย",
        example: "这场比赛我们输了。",
        examplePinyin: "Zhè chǎng bǐsài wǒmen shū le.",
        translation: "พวกเราแพ้การแข่งขันครั้งนี้",
    },

    {
        word: "充满",
        pinyin: "chōngmǎn",
        meaning: "เต็มไปด้วย, ล้นเหลือ",
        example: "这个城市充满了活力。",
        examplePinyin: "Zhège chéngshì chōngmǎn le huólì.",
        translation: "เมืองนี้เต็มไปด้วยพลังและชีวิตชีวา",
    },

    {
        word: "程序",
        pinyin: "chéngxù",
        meaning: "โปรแกรม, ขั้นตอน",
        example: "这个程序很容易使用。",
        examplePinyin: "Zhège chéngxù hěn róngyì shǐyòng.",
        translation: "โปรแกรมนี้ใช้งานง่ายมาก",
    },

    {
        word: "爱心",
        pinyin: "ài xīn",
        meaning: "ความรัก, ความเห็นอกเห็นใจ",
        example: "她用爱心帮助了很多人。",
        examplePinyin: "Tā yòng àixīn bāngzhù le hěn duō rén.",
        translation: "เธอช่วยเหลือผู้คนมากมายด้วยความเมตตา",
    },

    {
        word: "安慰",
        pinyin: "ānwèi",
        meaning: "ให้กำลังใจ, ช่วยบรรเทาความเจ็บปวด",
        example: "朋友安慰了我很久。",
        examplePinyin: "Péngyou ānwèi le wǒ hěn jiǔ.",
        translation: "เพื่อนให้กำลังใจฉันอยู่นาน",
    },

    {
        word: "安装",
        pinyin: "ānzhuāng",
        meaning: "ติดตั้ง, ติดตั้งซอฟต์แวร์",
        example: "我需要安装一个新的软件。",
        examplePinyin: "Wǒ xūyào ānzhuāng yí ge xīn de ruǎnjiàn.",
        translation: "ฉันต้องติดตั้งซอฟต์แวร์ใหม่หนึ่งโปรแกรม",
    },

    {
        word: "风景",
        pinyin: "fēngjǐng",
        meaning: "ทิวทัศน์, ภูมิทัศน์",
        example: "这里的风景非常漂亮。",
        examplePinyin: "Zhèlǐ de fēngjǐng fēicháng piàoliang.",
        translation: "ทิวทัศน์ที่นี่สวยมาก",
    },

    {
        word: "干完",
        pinyin: "gān wán",
        meaning: "ทำงานให้เสร็จ",
        example: "我终于干完今天的工作了。",
        examplePinyin: "Wǒ zhōngyú gān wán jīntiān de gōngzuò le.",
        translation: "ในที่สุดฉันก็ทำงานของวันนี้เสร็จแล้ว",
    },

    {
        word: "家具",
        pinyin: "jiājù",
        meaning: "เฟอร์นิเจอร์, ของใช้ในบ้าน",
        example: "我们买了一些新的家具。",
        examplePinyin: "Wǒmen mǎi le yìxiē xīn de jiājù.",
        translation: "พวกเราซื้อเฟอร์นิเจอร์ใหม่มาบางส่วน",
    },

    {
        word: "暗",
        pinyin: "àn",
        meaning: "มืด",
        example: "房间里太暗了。",
        examplePinyin: "Fángjiān lǐ tài àn le.",
        translation: "ในห้องมืดเกินไปแล้ว",
    },

    {
        word: "岸",
        pinyin: "àn",
        meaning: "ชายหาด, ฝั่ง",
        example: "我们坐在河岸边聊天。",
        examplePinyin: "Wǒmen zuò zài hé'àn biān liáotiān.",
        translation: "พวกเรานั่งคุยกันอยู่ริมฝั่งแม่น้ำ",
    },

    {
        word: "熬夜",
        pinyin: "áoyè",
        meaning: "นอนดึก, อดนอน",
        example: "不要经常熬夜。",
        examplePinyin: "Bú yào jīngcháng áoyè.",
        translation: "อย่านอนดึกเป็นประจำ",
    },

    {
        word: "把握",
        pinyin: "bǎwò",
        meaning: "ควบคุม, จับโอกาส",
        example: "我们一定要把握这个机会。",
        examplePinyin: "Wǒmen yídìng yào bǎwò zhège jīhuì.",
        translation: "พวกเราต้องคว้าโอกาสนี้ไว้ให้ได้",
    },

    {
        word: "整齐",
        pinyin: "zhěngqí",
        meaning: "เรียงลำดับ, จัดระเบียบ",
        example: "他的房间一直很整齐。",
        examplePinyin: "Tā de fángjiān yìzhí hěn zhěngqí.",
        translation: "ห้องของเขาเป็นระเบียบเรียบร้อยอยู่เสมอ",
    },

    {
        word: "保险",
        pinyin: "bǎoxiǎn",
        meaning: "ประกัน, ความคุ้มครอง",
        example: "我买了一份医疗保险。",
        examplePinyin: "Wǒ mǎi le yí fèn yīliáo bǎoxiǎn.",
        translation: "ฉันซื้อประกันสุขภาพหนึ่งฉบับ",
    },

    {
        word: "业务",
        pinyin: "yèwù",
        meaning: "งาน, ภารกิจ",
        example: "他的业务能力很强。",
        examplePinyin: "Tā de yèwù nénglì hěn qiáng.",
        translation: "ความสามารถในการทำงานของเขาแข็งแกร่งมาก",
    },

    {
        word: "办理",
        pinyin: "bànlǐ",
        meaning: "ดำเนินการ, จัดการ",
        example: "我需要去银行办理业务。",
        examplePinyin: "Wǒ xūyào qù yínháng bànlǐ yèwù.",
        translation: "ฉันต้องไปธนาคารเพื่อดำเนินการเรื่องต่างๆ",
    },

    {
        word: "傍晚",
        pinyin: "bàngwǎn",
        meaning: "เย็น, ตอนเย็น",
        example: "傍晚的时候，我们一起去散步。",
        examplePinyin: "Bàngwǎn de shíhou, wǒmen yìqǐ qù sànbù.",
        translation: "ตอนเย็นพวกเราไปเดินเล่นด้วยกัน",
    },

    {
        word: "包裹",
        pinyin: "bāoguǒ",
        meaning: "พัสดุ, หีบห่อ",
        example: "我的包裹已经到了。",
        examplePinyin: "Wǒ de bāoguǒ yǐjīng dào le.",
        translation: "พัสดุของฉันมาถึงแล้ว",
    },

    {
        word: "细节",
        pinyin: "xìjié",
        meaning: "รายละเอียด, จุดเล็กๆ",
        example: "请注意这些细节。",
        examplePinyin: "Qǐng zhùyì zhèxiē xìjié.",
        translation: "กรุณาใส่ใจกับรายละเอียดเหล่านี้",
    },

    {
        word: "电台",
        pinyin: "diàntái",
        meaning: "สถานีวิทยุ",
        example: "我喜欢听这个电台的节目。",
        examplePinyin: "Wǒ xǐhuan tīng zhège diàntái de jiémù.",
        translation: "ฉันชอบฟังรายการของสถานีวิทยุนี้",
    },

    {
        word: "恩爱",
        pinyin: "ēn'ài",
        meaning: "รักกัน, รักใคร่กัน",
        example: "他们夫妻一直很恩爱。",
        examplePinyin: "Tāmen fūqī yìzhí hěn ēn'ài.",
        translation: "สามีภรรยาคู่นี้รักใคร่กันดีเสมอ",
    },

    {
        word: "对比",
        pinyin: "duìbǐ",
        meaning: "เปรียบเทียบ",
        example: "我们可以对比一下这两个产品。",
        examplePinyin: "Wǒmen kěyǐ duìbǐ yíxià zhè liǎng ge chǎnpǐn.",
        translation: "เราสามารถเปรียบเทียบสินค้าสองชิ้นนี้ได้",
    },

    {
        word: "入围",
        pinyin: "rùwéi",
        meaning: "ผ่านเข้ารอบ, ได้รับการคัดเลือก",
        example: "他的作品成功入围了比赛。",
        examplePinyin: "Tā de zuòpǐn chénggōng rùwéi le bǐsài.",
        translation: "ผลงานของเขาผ่านเข้ารอบการแข่งขันสำเร็จ",
    },

    {
        word: "评委",
        pinyin: "píngwěi",
        meaning: "กรรมการประเมิน",
        example: "评委正在认真讨论。",
        examplePinyin: "Píngwěi zhèngzài rènzhēn tǎolùn.",
        translation: "คณะกรรมการกำลังหารือกันอย่างจริงจัง",
    },

    {
        word: "如何",
        pinyin: "rúhé",
        meaning: "อย่างไร, วิธีการ",
        example: "我们应该如何解决这个问题？",
        examplePinyin: "Wǒmen yīnggāi rúhé jiějué zhège wèntí?",
        translation: "พวกเราควรแก้ปัญหานี้อย่างไร?",
    },

    {
        word: "瘫痪",
        pinyin: "tānhuàn",
        meaning: "เป็นอัมพาต, ไม่สามารถทำงานได้",
        example: "电脑系统突然瘫痪了。",
        examplePinyin: "Diànnǎo xìtǒng tūrán tānhuàn le.",
        translation: "ระบบคอมพิวเตอร์เกิดขัดข้องจนไม่สามารถทำงานได้ทันที",
    },

    {
        word: "元旦",
        pinyin: "Yuándàn",
        meaning: "วันขึ้นปีใหม่",
        example: "元旦的时候，我们放假一天。",
        examplePinyin: "Yuándàn de shíhou, wǒmen fàngjià yì tiān.",
        translation: "ในวันขึ้นปีใหม่ พวกเราหยุดหนึ่งวัน",
    },

    {
        word: "意见",
        pinyin: "yìjiàn",
        meaning: "ความคิดเห็น, ข้อเสนอ",
        example: "你对这件事有什么意见？",
        examplePinyin: "Nǐ duì zhè jiàn shì yǒu shénme yìjiàn?",
        translation: "คุณมีความคิดเห็นอย่างไรเกี่ยวกับเรื่องนี้?",
    },

    {
        word: "廿",
        pinyin: "niàn",
        meaning: "ยี่สิบ",
        example: "“廿”是“二十”的意思。",
        examplePinyin: "“Niàn” shì “èrshí” de yìsi.",
        translation: "“廿” มีความหมายว่า “ยี่สิบ”",
    },

    {
        word: "给予",
        pinyin: "jǐyǔ",
        meaning: "ให้, มอบ",
        example: "谢谢你给予我的帮助。",
        examplePinyin: "Xièxie nǐ jǐyǔ wǒ de bāngzhù.",
        translation: "ขอบคุณสำหรับความช่วยเหลือที่คุณมอบให้ฉัน",
    },

    {
        word: "理论",
        pinyin: "lǐlùn",
        meaning: "ทฤษฎี, แนวคิด",
        example: "理论和实践都很重要。",
        examplePinyin: "Lǐlùn hé shíjiàn dōu hěn zhòngyào.",
        translation: "ทั้งทฤษฎีและการปฏิบัติล้วนสำคัญ",
    },

    {
        word: "实践",
        pinyin: "shíjiàn",
        meaning: "การปฏิบัติ, การนำไปใช้จริง",
        example: "我们应该把理论应用到实践中。",
        examplePinyin: "Wǒmen yīnggāi bǎ lǐlùn yìngyòng dào shíjiàn zhōng.",
        translation: "เราควรนำทฤษฎีไปประยุกต์ใช้ในการปฏิบัติจริง",
    },

    {
        word: "纪念",
        pinyin: "jìniàn",
        meaning: "รำลึก, ระลึกถึง",
        example: "我们举行活动来纪念这个重要的日子。",
        examplePinyin: "Wǒmen jǔxíng huódòng lái jìniàn zhège zhòngyào de rìzi.",
        translation: "พวกเราจัดกิจกรรมเพื่อรำลึกถึงวันสำคัญนี้",
    },

    {
        word: "特殊",
        pinyin: "tèshū",
        meaning: "พิเศษ, ไม่ธรรมดา",
        example: "今天是一个特殊的日子。",
        examplePinyin: "Jīntiān shì yí ge tèshū de rìzi.",
        translation: "วันนี้เป็นวันที่พิเศษ",
    },

    {
        word: "研究生",
        pinyin: "yánjiūshēng",
        meaning: "นักศึกษาระดับบัณฑิตศึกษา, นักศึกษาปริญญาโท",
        example: "我哥哥是一名研究生。",
        examplePinyin: "Wǒ gēge shì yì míng yánjiūshēng.",
        translation: "พี่ชายของฉันเป็นนักศึกษาระดับบัณฑิตศึกษา",
    },

    {
        word: "反对",
        pinyin: "fǎnduì",
        meaning: "ต่อต้าน, ไม่เห็นด้วย",
        example: "我反对这个决定。",
        examplePinyin: "Wǒ fǎnduì zhège juédìng.",
        translation: "ฉันไม่เห็นด้วยกับการตัดสินใจนี้",
    },

    {
        word: "相反",
        pinyin: "xiāngfǎn",
        meaning: "ตรงข้าม, ในทางตรงกันข้าม",
        example: "我不是生气，相反，我很开心。",
        examplePinyin: "Wǒ bú shì shēngqì, xiāngfǎn, wǒ hěn kāixīn.",
        translation: "ฉันไม่ได้โกรธ ในทางตรงกันข้าม ฉันมีความสุขมาก",
    },

    {
        word: "尊重",
        pinyin: "zūnzhòng",
        meaning: "เคารพ, ให้ความสำคัญ",
        example: "我们应该尊重别人的意见。",
        examplePinyin: "Wǒmen yīnggāi zūnzhòng biérén de yìjiàn.",
        translation: "เราควรเคารพความคิดเห็นของผู้อื่น",
    },

    {
        word: "选择",
        pinyin: "xuǎnzé",
        meaning: "เลือก, ตัดสินใจ",
        example: "你可以选择自己喜欢的方式。",
        examplePinyin: "Nǐ kěyǐ xuǎnzé zìjǐ xǐhuan de fāngshì.",
        translation: "คุณสามารถเลือกวิธีที่ตัวเองชอบได้",
    },

    {
        word: "娶",
        pinyin: "qǔ",
        meaning: "แต่งงานกับผู้หญิง",
        example: "他决定娶她为妻。",
        examplePinyin: "Tā juédìng qǔ tā wéi qī.",
        translation: "เขาตัดสินใจแต่งงานกับเธอ",
    },

    {
        word: "嫁",
        pinyin: "jià",
        meaning: "แต่งงานกับผู้ชาย",
        example: "她准备嫁给一个中国人。",
        examplePinyin: "Tā zhǔnbèi jià gěi yí ge Zhōngguó rén.",
        translation: "เธอเตรียมจะแต่งงานกับผู้ชายชาวจีนคนหนึ่ง",
    },

    {
        word: "饮食",
        pinyin: "yǐnshí",
        meaning: "อาหาร, การรับประทานอาหาร",
        example: "健康的饮食对身体很重要。",
        examplePinyin: "Jiànkāng de yǐnshí duì shēntǐ hěn zhòngyào.",
        translation: "การรับประทานอาหารที่ดีต่อสุขภาพสำคัญต่อร่างกายมาก",
    },

    {
        word: "印象",
        pinyin: "yìnxiàng",
        meaning: "ความประทับใจ, ภาพจำ",
        example: "他给我留下了很深的印象。",
        examplePinyin: "Tā gěi wǒ liúxià le hěn shēn de yìnxiàng.",
        translation: "เขาทำให้ฉันมีความประทับใจอย่างลึกซึ้ง",
    },

    {
        word: "美食",
        pinyin: "měishí",
        meaning: "อาหารอร่อย, อาหารพิเศษ",
        example: "这里有很多著名的美食。",
        examplePinyin: "Zhèlǐ yǒu hěn duō zhùmíng de měishí.",
        translation: "ที่นี่มีอาหารขึ้นชื่อมากมาย",
    },

    {
        word: "小吃",
        pinyin: "xiǎochī",
        meaning: "อาหารว่าง, ของกินเล่น, อาหารริมทาง",
        example: "这条街有很多特色小吃。",
        examplePinyin: "Zhè tiáo jiē yǒu hěn duō tèsè xiǎochī.",
        translation: "ถนนสายนี้มีอาหารว่างขึ้นชื่อมากมาย",
    },

    {
        word: "烤鸭",
        pinyin: "kǎoyā",
        meaning: "เป็ดย่าง",
        example: "北京烤鸭非常有名。",
        examplePinyin: "Běijīng kǎoyā fēicháng yǒumíng.",
        translation: "เป็ดย่างปักกิ่งมีชื่อเสียงมาก",
    },

    {
        word: "味道",
        pinyin: "wèidào",
        meaning: "รสชาติ, กลิ่น",
        example: "这道菜的味道很好。",
        examplePinyin: "Zhè dào cài de wèidào hěn hǎo.",
        translation: "อาหารจานนี้รสชาติดีมาก",
    },

    {
        word: "棒",
        pinyin: "bàng",
        meaning: "ดี, ยอดเยี่ยม",
        example: "你的中文说得真棒！",
        examplePinyin: "Nǐ de Zhōngwén shuō de zhēn bàng!",
        translation: "ภาษาจีนของคุณพูดได้ยอดเยี่ยมจริงๆ!",
    },

    {
        word: "口味",
        pinyin: "kǒuwèi",
        meaning: "รสชาติ, ความชอบในอาหาร",
        example: "每个人的口味都不一样。",
        examplePinyin: "Měi ge rén de kǒuwèi dōu bù yíyàng.",
        translation: "รสนิยมด้านอาหารของแต่ละคนไม่เหมือนกัน",
    },

    {
        word: "合",
        pinyin: "hé",
        meaning: "เหมาะสม, เข้ากัน",
        example: "这双鞋很合我的脚。",
        examplePinyin: "Zhè shuāng xié hěn hé wǒ de jiǎo.",
        translation: "รองเท้าคู่นี้พอดีกับเท้าของฉันมาก",
    },

    {
        word: "稍微",
        pinyin: "shāowēi",
        meaning: "เล็กน้อย, ไม่มาก",
        example: "请稍微等一下。",
        examplePinyin: "Qǐng shāowēi děng yíxià.",
        translation: "กรุณารอสักครู่นิดหนึ่ง",
    },

    {
        word: "淡",
        pinyin: "dàn",
        meaning: "ไม่เข้มข้น, อ่อน",
        example: "我喜欢喝淡一点的茶。",
        examplePinyin: "Wǒ xǐhuan hē dàn yìdiǎn de chá.",
        translation: "ฉันชอบดื่มชาที่รสอ่อนหน่อย",
    },

    {
        word: "血压",
        pinyin: "xuèyā",
        meaning: "ความดันโลหิต, ความดันเลือด",
        example: "他的血压有一点高。",
        examplePinyin: "Tā de xuèyā yǒu yìdiǎn gāo.",
        translation: "ความดันโลหิตของเขาค่อนข้างสูงเล็กน้อย",
    },

    {
        word: "盐",
        pinyin: "yán",
        meaning: "เกลือ",
        example: "这道菜放了太多盐。",
        examplePinyin: "Zhè dào cài fàng le tài duō yán.",
        translation: "อาหารจานนี้ใส่เกลือมากเกินไป",
    },

    {
        word: "辣",
        pinyin: "là",
        meaning: "เผ็ด, รสชาติเผ็ด",
        example: "这个菜太辣了。",
        examplePinyin: "Zhège cài tài là le.",
        translation: "อาหารจานนี้เผ็ดเกินไป",
    },

    {
        word: "嫩",
        pinyin: "nèn",
        meaning: "นุ่ม, ไม่แข็ง",
        example: "这块肉很嫩。",
        examplePinyin: "Zhè kuài ròu hěn nèn.",
        translation: "เนื้อชิ้นนี้นุ่มมาก",
    },

    {
        word: "浓",
        pinyin: "nóng",
        meaning: "เข้มข้น, เข้ม",
        example: "我喜欢喝浓一点的咖啡。",
        examplePinyin: "Wǒ xǐhuan hē nóng yìdiǎn de kāfēi.",
        translation: "ฉันชอบดื่มกาแฟที่เข้มขึ้นหน่อย",
    },

    {
        word: "中心",
        pinyin: "zhōngxīn",
        meaning: "ศูนย์กลาง, ใจกลาง",
        example: "这个城市位于国家的中心。",
        examplePinyin: "Zhège chéngshì wèi yú guójiā de zhōngxīn.",
        translation: "เมืองนี้ตั้งอยู่ที่ศูนย์กลางของประเทศ",
    },

    {
        word: "票务",
        pinyin: "piàowù",
        meaning: "การขายตั๋ว, บริการตั๋ว",
        example: "我想买演唱会的票。",
        examplePinyin: "Wǒ xiǎng mǎi yǎnchū huì de piào.",
        translation: "ฉันอยากซื้อตั๋วคอนเสิร์ต",
    },

    {
        word: "订",
        pinyin: "dìng",
        meaning: "จอง, ตกลง",
        example: "我订了一张机票。",
        examplePinyin: "Wǒ dìng le yì zhāng jīpiào.",
        translation: "ฉันจองตั๋วเครื่องบินไว้แล้ว",
    },

    {
        word: "香港",
        pinyin: "xiānggǎng",
        meaning: "ฮ่องกง",
        example: "我打算去香港旅行。",
        examplePinyin: "Wǒ dǎsuàn qù xiānggǎng lǚxíng.",
        translation: "ฉันวางแผนจะไปเที่ยวฮ่องกง",
    },

    {
        word: "机票",
        pinyin: "jīpiào",
        meaning: "ตั๋วเครื่องบิน",
        example: "我订了一张机票。",
        examplePinyin: "Wǒ dìng le yì zhāng jīpiào.",
        translation: "ฉันจองตั๋วเครื่องบินไว้แล้ว",
    },

    {
        word: "排队",
        pinyin: "páiduì",
        meaning: "คิว, จัดแถว",
        example: "人们在商店门口排队。",
        examplePinyin: "Rénmen zài shāngdiàn ménkǒu páiduì.",
        translation: "คนต่อคิวที่ประตูร้าน",
    },
    {
        word: "彩虹",
        pinyin: "cǎihóng",
        meaning: "รุ้ง, รุ้งที่เกิดขึ้นหลังฝนตก",
        example: "雨后出现了彩虹。",
        examplePinyin: "Yǔ hòu chūxiàn le cǎihóng.",
        translation: "หลังฝนตกก็มีรุ้งปรากฏขึ้น",
    },

    {
        word: "辛苦",
        pinyin: "xīnkǔ",
        meaning: "เหนื่อยล้า, ลำบาก",
        example: "他工作很辛苦。",
        examplePinyin: "Tā gōngzuò hěn xīnkǔ.",
        translation: "เขาทำงานยากมาก",
    },
    {
        word: "接",
        pinyin: "jiē",
        meaning: "รับ, ต่อ",
        example: "他接电话。",
        examplePinyin: "Tā jiē diànhuà.",
        translation: "เขาตอบโทรศัพท์",
    },
    {
        word: "机场",
        pinyin: "jīchǎng",
        meaning: "สนามบิน",
        example: "我们从机场出发。",
        examplePinyin: "Wǒmen cóng jīchǎng chūfā.",
        translation: "เราออกจากสนามบิน",
    },
    {
        word: "航班",
        pinyin: "hángbān",
        meaning: "เที่ยวบิน",
        example: "这架航班延误了。",
        examplePinyin: "Zhè jià hángbān yánwù le.",
        translation: "เที่ยวบินนี้ล่าช้า",
    },
    {
        word: "准时",
        pinyin: "zhǔnshí",
        meaning: "ตรงเวลา, ตามเวลา",
        example: "他总是准时到达。",
        examplePinyin: "Tā zǒngshì zhǔnshí dàodá.",
        translation: "เขาไปถึงตรงเวลาเสมอ",
    },
    {
        word: "行李",
        pinyin: "xíngli",
        meaning: "กระเป๋าเดินทาง",
        example: "我需要托运我的行李。",
        examplePinyin: "Wǒ xūyào tuōyùn wǒ de xíngli.",
        translation: "ฉันต้องส่งกระเป๋าเดินทางของฉัน",
    },
    {
        word: "托运",
        pinyin: "tuōyùn",
        meaning: "ส่งของ",
        example: "我需要托运我的行李。",
        examplePinyin: "Wǒ xūyào tuōyùn wǒ de xíngli.",
        translation: "ฉันต้องส่งกระเป๋าเดินทางของฉัน",
    },
    {
        word: "河流",
        pinyin: "héliú",
        meaning: "แม่น้ำ",
        example: "这条河流很宽。",
        examplePinyin: "Zhè tiáo héliú hěn kuān.",
        translation: "แม่น้ำนี้กว้างมาก",
    },
    {
        word: "海洋",
        pinyin: "hǎiyáng",
        meaning: "มหาสมุทร",
        example: "他在海洋中游泳。",
        examplePinyin: "Tā zài hǎiyáng zhōng yóuyǒng.",
        translation: "เขาว่ายน้ำในมหาสมุทร",
    },
    {
        word: "抱歉",
        pinyin: "bàoqiàn",
        meaning: "ขอโทษ, ขอโทษที่ทำให้ผิดหวัง",
        example: "对不起，我迟到了。",
        examplePinyin: "Duìbuqǐ, wǒ chídào le.",
        translation: "ขอโทษครับ ฉันมาสาย",
    },
    {
        word: "抬起",
        pinyin: "tāiqǐ",
        meaning: "ยกขึ้น, ยก",
        example: "他抬起手。",
        examplePinyin: "Tāi qǐ shǒu.",
        translation: "เขายกมือขึ้น",
    },
    {
        word: "愉快",
        pinyin: "yúkuài",
        meaning: "สนุก, พอใจ",
        example: "我们度过了愉快的一天。",
        examplePinyin: "Wǒmen dùguò le yúkuài de yītiān.",
        translation: "เราผ่านวันที่สนุกสนาน",
    },
    {
        word: "害怕",
        pinyin: "hàipà",
        meaning: "กลัว, กลัว",
        example: "他害怕黑暗。",
        examplePinyin: "Tā hàipà hēi'àn.",
        translation: "เขากลัวความมืด",
    },
    {
        word: "讨论",
        pinyin: "tǎolùn",
        meaning: "พูดคุย, หารือ",
        example: "我们讨论了一下这个问题。",
        examplePinyin: "Wǒmen tǎolùn le yīxià zhège wèntí.",
        translation: "เราหารือเกี่ยวกับปัญหานี้แล้ว",
    },
    {
        word: "说明",
        pinyin: "shuōmíng",
        meaning: "อธิบาย, ชี้แจ้ง",
        example: "请说明一下你的观点。",
        examplePinyin: "Qǐng shuōmíng yīxià nǐ de guāndiǎn.",
        translation: "โปรดอธิบายมุมมองของคุณ",
    },
    {
        word: "迷路",
        pinyin: "mílù",
        meaning: "หลงทาง",
        example: "我迷路了。",
        examplePinyin: "Wǒ mílù le.",
        translation: "ฉันหลงทาง",
    },
    {
        word: "迟到",
        pinyin: "chídào",
        meaning: "มาสาย",
        example: "我迟到了。",
        examplePinyin: "Wǒ chídào le.",
        translation: "ฉันมาสาย",
    },
    {
        word: "疾病",
        pinyin: "jíbìng",
        meaning: "โรค",
        example: "他患有高血压。",
        examplePinyin: "Tā huàn yǒu gāoyāxuè.",
        translation: "เขาเป็นโรคความดันโลหิตสูง",
    },
    {
        word: "疼痛",
        pinyin: "téngtòng",
        meaning: "ปวด, ปวด",
        example: "他的头很疼。",    
        examplePinyin: "Tā de tóu hěn téng.",
        translation: "หัวของเขาเจ็บมาก",
    },
    {
        word: "植物",
        pinyin: "zhíwù",
        meaning: "พืช",
        example: "这些植物很美丽。",
        examplePinyin: "Zhèxiē zhíwù hěn měilì.",
        translation: "พืชเหล่านี้สวยงามมาก",
    },
    {
        word: "药材",
        pinyin: "yàocái",
        meaning: "ยาสมุนไพร, วัตถุที่ใช้ทำยา",
        example: "这是一些药材。",
        examplePinyin: "Zhè shì yīxiē yàocái.",
        translation: "นี่คือสมุนไพรบางชนิด",
    },
    {
        word: "钢铁",
        pinyin: "gāngtiě",
        meaning: "เหล็ก, โลหะ",
        example: "这是一块钢铁。",
        examplePinyin: "Zhè shì yī kuài gāngtiě.",
        translation: "นี่คือชิ้นเหล็กหนึ่งชิ้น",
    },
    {
        word: "钥匙",
        pinyin: "yàoshi",
        meaning: "กุญแจ",
        example: "我找不到我的钥匙了。",
        examplePinyin: "Wǒ zhǎo bù dào wǒ de yàoshi le.",
        translation: "ฉันหากุญแจของฉันไม่เจอ",
    },
    {
        word: "饼干",
        pinyin: "bǐnggān",
        meaning: "คุกกี้, ขนมปังแห้ง",
        example: "我吃了一块饼干。",
        examplePinyin: "Wǒ chī le yī kuài bǐnggān.",
        translation: "ฉันกินคุกกี้หนึ่งชิ้น",
    },
    {
        word: "饥饿",
        pinyin: "jī'è",
        meaning: "หิว, อดอาหาร",
        example: "我饥饿了。",
        examplePinyin: "Wǒ jī'è le.",
        translation: "ฉันหิวแล้ว",
    },
    {
        word: "衬衫",
        pinyin: "chēnshān",
        meaning: "เสื้อเชิ้ต",
        example: "我穿了一件衬衫。",
        examplePinyin: "Wǒ chuān le yī jiàn chēnshān.",
        translation: "ฉันใส่เสื้อเชิ้ตชิ้นหนึ่ง",
    },
    {
        word: "裤子",
        pinyin: "kùzi",
        meaning: "กางเกง",
        example: "我穿了一条裤子。",
        examplePinyin: "Wǒ chuān le yī tiáo kùzi.",
        translation: "ฉันใส่กางเกงหนึ่งตัว",
    },
    {
        word: "提高",
        pinyin: "tígāo",
        meaning: "เพิ่มขึ้น, ปรับปรุง",
        example: "我们要提高自己的能力。",
        examplePinyin: "Wǒmen yào tígāo zìjǐ de nénglì.",
        translation: "เราต้องปรับปรุงความสามารถของตัวเอง",
    },
    {
        word: "降低",
        pinyin: "jiàngdī",
        meaning: "ลดลง, ปรับต่ำ",
        example: "我们要降低自己的期望。",
        examplePinyin: "Wǒmen yào jiàngdī zìjǐ de qīwàng.",
        translation: "เราต้องลดความคาดหวังของตัวเอง",
    },
    {
        word: "增加",
        pinyin: "zēngjiā",
        meaning: "เพิ่ม, ขยาย",
        example: "我们要增加自己的知识。",
        examplePinyin: "Wǒmen yào zēngjiā zìjǐ de zhīshì.",
        translation: "เราต้องเพิ่มความรู้ของตัวเอง",
    },
    {
        word: "减少",
        pinyin: "jiǎnshǎo",
        meaning: "ลดลง, ลดจำนวน",
        example: "我们要减少自己的开支。",
        examplePinyin: "Wǒmen yào jiǎnshǎo zìjǐ de kāizhī.",
        translation: "เราต้องลดค่าใช้จ่ายของตัวเอง",
    },
    {
        word: "扩大",
        pinyin: "kuòdà",
        meaning: "ขยาย, ขยายขนาด",
        example: "我们要扩大自己的视野。",
        examplePinyin: "Wǒmen yào kuòdà zìjǐ de shìyě.",
        translation: "เราต้องขยายขอบเขตของตัวเอง",
    },
    {
        word: "缩小",
        pinyin: "suo'xiao",
        meaning: "ลดลง, ย่อลง",
        example: "我们要缩小自己的期望。",
        examplePinyin: "Wǒmen yào suo'xiao zìjǐ de qīwàng.",
        translation: "เราต้องลดความคาดหวังของตัวเอง",
    },
    {
        word: "接受",
        pinyin: "jiēshòu",
        meaning: "รับ, ยอมรับ",
        example: "我接受了这个提议。",
        examplePinyin: "Wǒ jiēshòu le zhège tíyì.",
        translation: "ฉันยอมรับข้อเสนอแห่งนี้",
    },
    {
        word: "拒绝",
        pinyin: "jùjué",
        meaning: "ปฏิเสธ, ไม่ยอมรับ",
        example: "我拒绝了他的提议。",
        examplePinyin: "Wǒ jùjué le tā de tíyì.",
        translation: "ฉันปฏิเสธข้อเสนอของเขา",
    },
    {
        word: "成功",
        pinyin: "chénggōng",
        meaning: "ประสบความสำเร็จ, สำเร็จ",
        example: "我们成功了。",
        examplePinyin: "Wǒmen chénggōng le.",
        translation: "เราสำเร็จแล้ว",
    },
    {
        word: "失败",
        pinyin: "shībài",
        meaning: "ล้มเหลว, ไม่สำเร็จ",
        example: "我们失败了。",
        examplePinyin: "Wǒmen shībài le.",
        translation: "เราล้มเหลวแล้ว",
    },
    {
        word: "优点",
        pinyin: "yōudiǎn",
        meaning: "ข้อดี, จุดแข็ง",
        example: "这个产品有很多优点。",
        examplePinyin: "Zhège chǎnpǐn yǒu hěn duō yōudiǎn.",
        translation: "ผลิตภัณฑ์นี้มีข้อดีหลายประการ",
    },
    {
        word: "缺点",
        pinyin: "quēdiǎn",
        meaning: "ข้อเสีย, จุดอ่อน",
        example: "这个产品也有很多缺点。",
        examplePinyin: "Zhège chǎnpǐn yǒu yě hěn duō quēdiǎn.",
        translation: "ผลิตภัณฑ์นี้มีข้อเสียหลายประการ",
    },
    {
        word: "熟悉",
        pinyin: "shúxī",
        meaning: "คุ้นเคย, รู้จัก",
        example: "我熟悉这个地方。",
        examplePinyin: "Wǒ shúxī zhège dìfāng.",
        translation: "ฉันคุ้นเคยกับสถานที่นี้",
    },
    {
        word: "陌生",
        pinyin: "mòshēng",
        meaning: "แปลก, ไม่คุ้นเคย",
        example: "我在这个城市感到很陌生。",
        examplePinyin: "Wǒ zài zhège chéngshì gǎndào hěn mòshēng.",
        translation: "ฉันรู้สึกแปลกใจในเมืองนี้",
    },
    {
        word: "积极",
        pinyin: "jījí",
        meaning: "กระตือรือร้น, สนใจ",
        example: "我们要积极地参与这个项目。",
        examplePinyin: "Wǒmen yào jījí de cānyù zhège xiàngmù.",
        translation: "เราต้องเข้าร่วมโครงการนี้อย่างกระตือรือร้น",
    },
    {
        word: "消极",
        pinyin: "xiāojí",
        meaning: "เฉื่อยชา, ไม่สนใจ",
        example: "他总是很消极。",
        examplePinyin: "Tā zǒngshì hěn xiāojí.",
        translation: "เขาเป็นคนที่เฉื่อยชาเสมอ",
    },
    {
        word: "具体",
        pinyin: "jùtǐ",
        meaning: "เฉพาะเจาะจง, รายละเอียด",
        example: "我们需要具体的计划。",
        examplePinyin: "Wǒmen xūyào jùtǐ de jìhuà.",
        translation: "เราต้องการแผนที่ชัดเจน",
    },
    {
        word: "抽象",
        pinyin: "chōuxiàng",
        meaning: "นามธรรม, ไม่มีรูปร่าง",
        example: "这是一个抽象的概念。",
        examplePinyin: "Zhège shì yīgè chōuxiàng de gàiniàn.",
        translation: "นี่คือแนวคิดนามธรรม",
    },
    {
        word: "暂时",
        pinyin: "zànshí",
        meaning: "ชั่วคราว, ระยะสั้น",
        example: "我暂时离开一下。",
        examplePinyin: "Wǒ zànshí líkāi yīxià.",
        translation: "ฉันจะไปไหนสักครู่",
    },
    {
        word: "永久",
        pinyin: "yǒngjiǔ",
        meaning: "ถาวร, ตลอดกาล",
        example: "这是一个永久的承诺。",
        examplePinyin: "Zhège shì yīgè yǒngjiǔ de chéngnuò.",
        translation: "นี่คือคำสัญญาที่ถาวร",
    },
    {
        word: "感冒",
        pinyin: "gǎnmào",
        meaning: "หวัด, ปอด inflamed",
        example: "我感冒了。",
        examplePinyin: "Wǒ gǎnmào le.",
        translation: "ฉันเป็นหวัด",
    },
    {
        word: "抱怨",
        pinyin: "bàoyuàn",
        meaning: "ร้องเรียน, ไม่พอใจ",
        example: "他对这个决定感到抱怨。",
        examplePinyin: "Tā duì zhège juédìng gǎndào bàoyuàn.",
        translation: "เขาไม่พอใจกับการตัดสินใจนี้",
    },
    {
        word: "串",
        pinyin: "chuàn",
        meaning: "โซ่, สาย",
        example: "他手里拿着一串钥匙。",
        examplePinyin: "Tā shǒu lǐ ná zhe yī chuàn yàoshi.",
        translation: "เขาถือกุญแจเป็นโซ่ในมือ",
    },
    {
        word: "农村",
        pinyin: "nóngcūn",
        meaning: "หมู่บ้าน, ชนบท",
        example: "他住在农村。",
        examplePinyin: "Tā zhù zài nóngcūn.",
        translation: "เขาอาศัยอยู่ในหมู่บ้าน",
    },
    {
        word: "断",
        pinyin: "duàn",
        meaning: "หยุด, ขาด",
        example: "他断了电话。",
        examplePinyin: "Tā duàn le diànhuà.",
        translation: "เขาตัดสายโทรศัพท์",
    },
    {
        word: "姥姥",
        pinyin: "lǎolao",
        meaning: "ปู่, ยาย",
        example: "我的姥姥很慈祥。",
        examplePinyin: "Wǒ de lǎolao hěn cíxiáng.",
        translation: "ปู่ของฉันน่ารักมาก",
    },
    {
        word: "舅舅",
        pinyin: "jiùjiu",
        meaning: "ลุง, ป้า",
        example: "我的舅舅是医生。",
        examplePinyin: "Wǒ de jiùjiu shì yīsheng.",
        translation: "ลุงของฉันเป็นหมอ",
    },
    {
        word: "姑姑",
        pinyin: "gūgū",
        meaning: "ป้า, ยาย",
        example: "我的姑姑很温柔。",
        examplePinyin: "Wǒ de gūgū hěn wēnróu.",
        translation: "ป้าของฉันน่ารักมาก",
    },
    {
        word: "坚决",
        pinyin: "jiānjué",
        meaning: "ยืนยัน, ไม่เปลี่ยนใจ",
        example: "他坚决不同意这个决定。",
        examplePinyin: "Tā jiānjué bù tóngyì zhège juédìng.",
        translation: "เขาไม่ยอมรับการตัดสินใจนี้",
    },
    {
        word: "打工",
        pinyin: "dǎgōng",
        meaning: "ทำงานหนัก, ทำงานเพื่อรายได้",
        example: "他每天都在工厂打工。",
        examplePinyin: "Tā měitiān dōu zài gōngchǎng dǎgōng.",
        translation: "เขาทำงานที่โรงงานทุกวัน",
    },
    {
        word: "挣",
        pinyin: "zhēng",
        meaning: "ได้เงิน, ทำงานเพื่อรายได้",
        example: "他努力挣钱养家。",
        examplePinyin: "Tā nǔlì zhēngqián yǎngjiā.",
        translation: "เขาทำงานหนักเพื่อ kiếmเงินเลี้ยงครอบครัว",
    },
    {
        word: "装修",
        pinyin: "zhuāngxiū",
        meaning: "ตกแต่ง, ปรับปรุง",
        example: "他们正在装修新家。",
        examplePinyin: "Tāmen zhèngzài zhuāngxiū xīnjiā.",
        translation: "พวกเขากำลังตกแต่งบ้านใหม่",
    },
    {
        word: "醉",
        pinyin: "zuì",
        meaning: "เมา, ดื่มเหล้า",
        example: "他喝醉了。",
        examplePinyin: "Tā hē zuì le.",
        translation: "เขาดื่มเหล้าเมา",
    },
    {
        word: "锁",
        pinyin: "suǒ",
        meaning: "กุญแจ, ล็อก",
        example: "他把门锁上了。",
        examplePinyin: "Tā bǎ mén suǒ shàng le.",
        translation: "เขาปิดล็อกประตู",
    },
    {
        word: "临",
        pinyin: "lín",
        meaning: "ใกล้, อยู่ใกล้",
        example: "他住在学校附近。",
        examplePinyin: "Tā zhù zài xuéxiào fùjìn.",
        translation: "เขาอาศัยอยู่ใกล้โรงเรียน",
    },
    {
        word: "强烈",
        pinyin: "qiángliè",
        meaning: "รุนแรง, มาก",
        example: "他感到强烈的情绪波动。",
        examplePinyin: "Tā gǎndào qiángliè de qíngxù bōdòng.",
        translation: "เขารู้สึกอารมณ์ที่รุนแรง",
    },
    {
        word: "悄悄",
        pinyin: "qiāoqiāo",
        meaning: "เงียบ, ไม่เปิดเผย",
        example: "他悄悄地走进房间。",
        examplePinyin: "Tā qiāoqiāo de zǒujìn fángjiān.",
        translation: "เขาเดินเข้าไปในห้องอย่างเงียบ",
    },
    {
        word: "晒",
        pinyin: "shài",
        meaning: "แดด, แสงแดด",
        example: "太阳很晒。",
        examplePinyin: "Tàiyáng hěn shài.",
        translation: "แดดแรง",
    },
    {
        word: "被子",
        pinyin: "bèizi",
        meaning: "ผ้าห่ม",
        example: "他盖着被子睡觉。",
        examplePinyin: "Tā gài zhe bèizi shuìjiào.",
        translation: "เขาใช้ผ้าห่มนอน",
    },
    {
        word: "长途",
        pinyin: "chángtú",
        meaning: "ระยะไกล",
        example: "他要去长途旅行。",
        examplePinyin: "Tā yào qù chángtú lǚxíng.",
        translation: "เขาจะไปเที่ยวระยะไกล",
    },
    {
        word: "冻",
        pinyin: "dòng",
        meaning: "เย็น, แช่แข็ง",
        example: "天气很冻。",
        examplePinyin: "Tiānqì hěn dòng.",
        translation: "อากาศเย็น",

    },
    {
        word: "想象",
        pinyin: "xiǎngxiàng",
        meaning: "คิด, จินตนาการ",
        example: "他想象着美好的未来。",
        examplePinyin: "Tā xiǎngxiàng zhe měihǎo de wèilái.",
        translation: "เขาคิดถึงอนาคตที่ดี",
    },
    {
        word: "灰尘",
        pinyin: "huīchén",
        meaning: "ฝุ่น, คราบฝุ่น",
        example: "房间里有很多灰尘。",
        examplePinyin: "Fángjiān lǐ yǒu hěn duō huīchén.",
        translation: "ในห้องมีฝุ่นเยอะ",
    },
    {
        word: "微笑",
        pinyin: "wēixiào",
        meaning: "รอยยิ้ม, ความสุข",
        example: "她对我微笑。",
        examplePinyin: "Tā duì wǒ wēixiào.",
        translation: "เธอยิ้มให้ฉัน",
    },
    {
        word: "温暖",
        pinyin: "wēnnuǎn",
        meaning: "อบอุ่น, อบอุ่น",
        example: "房间里的温度很温暖。",
        examplePinyin: "Fángjiān lǐ de wēndù hěn wēnnuǎn.",
        translation: "อุณหภูมิในห้องอบอุ่น",
    },
    {
        word: "立刻",
        pinyin: "lìkè",
        meaning: "ทันที, ทันท่วง",
        example: "他立刻回答了问题。",
        examplePinyin: "Tā lìkè huídá le wèntí.",
        translation: "เขาตอบคำถามทันที",
    },
    {
        word: "扑",
        pinyin: "pū",
        meaning: "กระเด็น, กระเด็น",
        example: "他扑向了目标。",
        examplePinyin: "Tā pū xiàng le mùbiāo.",
        translation: "เขากระเด็นไปยังเป้าหมาย",
    },
    {
        word: "卧室",
        pinyin: "wòshì",
        meaning: "ห้องนอน",
        example: "他走进卧室。",
        examplePinyin: "Tā zǒu jìn wòshì.",
        translation: "เขาเดินเข้าไปในห้องนอน",
    },
    {
        word: "铺",
        pinyin: "pū",
        meaning: "วาง, วาง",
        example: "他铺开了毯子。",
        examplePinyin: "Tā pū kāi le tǎnzǐ.",
        translation: "เขาวางผ้าห่ม",
    },
    {
        word: "飘",
        pinyin: "piāo",
        meaning: "ลอย, ลอย",
        example: "花瓣在风中飘舞。",
        examplePinyin: "Huābàn zài fēng zhōng piāo wǔ.",
        translation: "ใบไม้ลอยในลม",
    },
    {
        word: "阵",
        pinyin: "zhèn",
        meaning: "แถว, แนว",
        example: "士兵们排成了一阵。",
        examplePinyin: "Shìbīng men pái chéng le yī zhèn.",
        translation: "ทหารวางเป็นแถว",
    },
    {
        word: "感受",
        pinyin: "gǎnshòu",
        meaning: "ความรู้สึก, ความเข้าใจ",
        example: "他感受到了温暖。",
        examplePinyin: "Tā gǎnshòu le wēnnuǎn.",
        translation: "เขาได้รับรู้ถึงความอบอุ่น",
    },
    {
        word: "流泪",
        pinyin: "liúlèi",
        meaning: "น้ำตา, น้ำตา",
        example: "他流泪了。",
        examplePinyin: "Tā liúlèi le.",
        translation: "เขาไหล่น้ำตา",
    },
    {
        word: "县",
        pinyin: "xiàn",
        meaning: "เขต, อำเภอ",
        example: "他住在县城里。",
        examplePinyin: "Tā zhù zài xiàn chéng lǐ.",
        translation: "เขาอาศัยอยู่ในเขตเมือง",
    },
    {
        word: "以来",
        pinyin: "yǐlái",
        meaning: "ตั้งแต่, ตั้งแต่",
        example: "他以来就住在那。",
        examplePinyin: "Tā yǐlái jiù zhù zài nà.",
        translation: "เขาอาศัยอยู่ที่นั่นตั้งแต่",
    },
    {
        word: "一辈子",
        pinyin: "yíbèi",
        meaning: "ตลอดชีวิต, ตลอดชีวิต",
        example: "他一辈子都住在那。",
        examplePinyin: "Tā yíbèi zǐ dōu zhù zài nà.",
        translation: "เขาอาศัยอยู่ที่นั่นตลอดชีวิต",
    },
    {
        word: "屋子",
        pinyin: "wūzi",
        meaning: "ห้อง, บ้าน",
        example: "他走进了屋子。",
        examplePinyin: "Tā zǒu jìn le wūzi.",
        translation: "เขาเดินเข้าไปในห้อง",
    },
    {
        word: "脑袋",
        pinyin: "nǎo dai",
        meaning: "หัว, สมอง",
        example: "他用脑袋思考。",
        examplePinyin: "Tā yòng nǎo dài sīkǎo.",
        translation: "เขาใช้สมองคิด",
    },
    {
        word: "叙述",
        pinyin: "xùshù",
        meaning: "การบรรยาย, การเล่าเรื่อง",
        example: "他叙述了事件的经过。",
        examplePinyin: "Tā xùshù le shìjiàn de jīngguò.",
        translation: "เขาเล่าเรื่องราวของเหตุการณ์",
    },
    {
        word: "婚姻",
        pinyin: "hūnyīn",
        meaning: "การสมรส, การแต่งงาน",
        example: "他们结婚了。",
        examplePinyin: "Tāmen jiéhūn le.",
        translation: "พวกเขาแต่งงานแล้ว",
    },
    {
        word: "肩膀",
        pinyin: "jiānbǎng",
        meaning: "ไหล่, ไหล่",
        example: "他靠着肩膀。",
        examplePinyin: "Tā kào zhe jiānbǎng.",
        translation: "เขา leaning on the shoulder",
    },
    {
        word: "蚊子",
        pinyin: "wénzi",
        meaning: "แมลงวัน, แมลงวัน",
        example: "蚊子咬了他。",
        examplePinyin: "Wénzi yǎo le tā.",
        translation: "แมลงวันกัดเขา",
    },
    {
        word: "半夜",
        pinyin: "bànyè",
        meaning: "กลางคืน, ตอนกลางคืน",
        example: "他半夜起床了。",
        examplePinyin: "Tā bànyè qǐchuáng le.",
        translation: "เขาตื่นตอนกลางคืน",
    },
    {
        word: "歪歪扭扭",
        pinyin: "wāiwāi niǔniǔ",
        meaning: "เบี้ยว, ไม่ตรง",
        example: "他走路歪歪扭扭的。",
        examplePinyin: "Tā zǒulù wāiwāi niǔniǔ de.",
        translation: "เขาเดินแบบเบี้ยว",
    },
];